name: TownyConquered
main: com.bitbucket.fcdev.townyconquered.TownyConquered
version: 1.0
api-version: 1.13
depend:
  - Towny
commands:
  setconqueror:
    description: Imposta la nazione che controlla la città
    usage: /setconquered <town> <nation> <days> <tax> <tax_type>
    permission: townyconquered.admin.command.setconquered
permissions:
  townyconquered.admin.command.setconquered:
    default: op
