name: TownyConquered
main: it.ancientrealms.townyconquered.TownyConquered
version: 1.0.0
api-version: 1.13
depend:
  - Towny
commands:
  setconquered:
    description: Imposta la nazione che controlla la città
    usage: /setconquered [conquered_town] [new_nation] [days] [tax] [tax_type]
    permission: townyconquered.admin.command.setconquered
permissions:
  townyconquered.admin.command.setconquered:
    default: op
