name: TownyConquered
main: it.ancientrealms.townyconquered.TownyConquered
version: 1.0.0
api-version: 1.13
depend:
  - Towny
commands:
  setconquered:
    description: Imposta la nazione che controlla la città
    usage: /setconquered [conquered_town] [new_nation] [days] [tax] [tax_type]
    permission: townyconquered.admin.command.setconquered
  removeconquered:
    description: Rimuovi la città come conquistata
    usage: /removeconquered [town]
    permission: townyconquered.admin.command.removeconquered
permissions:
  townyconquered.admin.command.setconquered:
    default: op
  townyconquered.admin.command.removeconquered:
    default: op
